services: 
  postgres:
    image: postgres:13 
    restart: always
    container_name: postgres_db 
    environment:
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: movie_theater_lab 
      POSTGRES_USER: labuser
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_output:/tmp
      - ./init/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql:ro
    networks:
      - db-network
    ports:
      - "5432:5432"

volumes: 
  pgdata:

networks:
  db-network: