services: 
  postgres:
    image: postgres:13 
    restart: always
    container_name: postgres_db 
    environment:
      POSTGRES_PASSWORD: example_password 
      POSTGRES_DB: example_db 
      POSTGRES_USER: example_user
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-network
    ports:
      - "5432:5432"

volumes: 
  pgdata:

networks:
  db-network: